obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.29, -0.28], [-0.29, 0.28], [0.29, 0.28], [0.29, -0.28]] #scout_mini
#robot_radius: ir_of_robot
# robot_radius: 0.25  # xbot
inflation_radius: 0.3

observation_sources: laser_scan_sensor

# laser_scan_sensor: {sensor_frame: fake_laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}