obstacle_range: 2.5
raytrace_range: 3.0

# scout_mini 的尺寸是 627mm * 549mm，0.627m * 0.549m
# 0.627/2 = 0.3135, 0.549/2 = 0.2745
# footprint: [[-0.29, -0.28], [-0.29, 0.28], [0.29, 0.28], [0.29, -0.28]] 
footprint: [[-0.3135, -0.2745], [-0.3135, 0.2745], [0.3135, 0.2745], [0.3135, -0.2745]] 
# robot_radius: ir_of_robot
# robot_radius: 0.25  # xbot

inflation_radius: 0.3

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}