global_costmap:
  # global_frame: map
  global_frame: map
  robot_base_frame: base_link #used for scout_mini
  # robot_base_frame: base_footprint #used for x-bot
  # robot_base_frame: odom
  update_frequency: 5.0
  static_map: true